/* Generated By:JJTree: Do not edit this line. D:/cvs/main/src/org/nfunk/jep\ParserVisitor.java */

/**
 * $RCSfile: ParserVisitor.java,v $
 * $Revision: 1.0 $
 * $Date: 2025/08/25 $
 * <p>
 * Copyright (c) 2025 ooder.net
 * </p>
 * <p>
 * Company: ooder.net
 * </p>
 * <p>
 * License: MIT License
 * </p>
 */
package net.ooder.common.expression;

public interface ParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTStart node, Object data);
  public Object visit(ASTFunNode node, Object data);
  public Object visit(ASTVarNode node, Object data);
  public Object visit(ASTConstant node, Object data);
}
