package net.ooder.annotation.ui;


import net.ooder.annotation.IconEnumstype;

// 保留前三个已经正确升级的图标
public enum CustomImageType implements IconEnumstype {
    o("ri-calendar-line", "ri-calendar-line"),
    close("ri-close-line", "ri-close-line"),
    notch("ri-loader-line", "ri-loader-line"),
    div("ri-checkbox-blank-line","ri-checkbox-blank-line"),

    dialog("ri-window-line", "ri-window-line"),
    data("ri-database-line", "ri-database-line"),
    debug("ri-bug-line", "ri-bug-line"),
    debug1("ri-flask-line", "ri-flask-line"),
    video("ri-video-line", "ri-video-line"),
    webapi("ri-server-line", "ri-server-line"),
    cut("ri-scissors-line", "ri-scissors-line"),
    delete("ri-delete-bin-line", "ri-delete-bin-line"),
    designview("ri-paint-brush-line", "ri-paint-brush-line"),
    icondomnode("ri-git-branch-line", "ri-git-branch-line"),
    deletepath("ri-link-unlink", "ri-link-unlink"),
    edit("ri-edit-line", "ri-edit-line"),
    deletefile("ri-file-excel-line", "ri-file-excel-line"),
    event("ri-flashlight-line", "ri-flashlight-line"),
    editpath("ri-link", "ri-link"),
    empty("ri-archive-line", "ri-archive-line"),
    file("ri-file-line", "ri-file-line"),
    explore("ri-search-line", "ri-search-line"),
    fillcell("ri-paint-fill", "ri-paint-fill"),
    filexml("ri-file-code-line", "ri-file-code-line"),
    formatjs("ri-file-code-line", "ri-file-code-line"),
    formatjson("ri-file-transfer-line", "ri-file-transfer-line"),
    frame("ri-box-2-line", "ri-box-2-line"),
    hmirror("ri-arrow-left-right-line", "ri-arrow-left-right-line"),
    hash("ri-hashtag", "ri-hashtag"),
    function("ri-settings-3-line", "ri-settings-3-line"),
    gallery("ri-gallery-line", "ri-gallery-line"),
    html("ri-code-line", "ri-code-line"),
    arrowtop("ri-arrow-up-line", "ri-arrow-up-line"),
    bigup("ri-arrow-up-circle-line", "ri-arrow-up-circle-line"),
    indent("ri-indent-increase", "ri-indent-increase"),
    js("ri-javascript-line", "ri-javascript-line"),
    jumpto("ri-arrow-go-forward-line", "ri-arrow-go-forward-line"),
    language("ri-translate-2", "ri-translate-2"),
    sfile("ri-file-code-line", "ri-file-code-line"),
    manual("ri-book-line", "ri-book-line"),
    links("ri-link", "ri-link"),
    login("ri-login-box-line", "ri-login-box-line"),
    movebackward("ri-arrow-left-line", "ri-arrow-left-line"),
    module("ri-box-2-line", "ri-box-2-line"),
    down("ri-arrow-down-s-line", "ri-arrow-down-s-line"),
    moveforward("ri-arrow-right-line", "ri-arrow-right-line"),
    up("ri-arrow-up-s-line", "ri-arrow-up-s-line"),
    newfile("ri-file-transfer-line", "ri-file-transfer-line"),
    newprj("ri-node-tree", "ri-node-tree"),
    ok("ri-check-line", "ri-check-line"),
    openprj("ri-folder-open-line", "ri-folder-open-line"),
    iconpackage("ri-box-2-line", "ri-box-2-line"),
    options("ri-settings-line", "ri-settings-line"),
    page("ri-file-text-line", "ri-file-text-line"),
    phonegap("ri-smartphone-line", "ri-smartphone-line"),
    paste("ri-clipboard-line", "ri-clipboard-line"),
    pic("ri-image-line", "ri-image-line"),
    previewpage("ri-eye-line", "ri-eye-line"),
    preview("ri-eye-line", "ri-eye-line"),
    property("ri-slideshow-line", "ri-slideshow-line"),
    rename("ri-edit-line", "ri-edit-line"),
    project("ri-node-tree", "ri-node-tree"),
    rendermode("ri-palette-line", "ri-palette-line"),
    resetpath("ri-refresh-line", "ri-refresh-line"),
    rotateleft("ri-arrow-go-back-line", "ri-arrow-go-back-line"),
    rotateright("ri-arrow-go-forward-line", "ri-arrow-go-forward-line"),
    rpc("ri-server-line", "ri-server-line"),
    save("ri-save-line", "ri-save-line"),
    saveall("ri-save-line", "ri-save-line"),
    searchreplace("ri-search-line", "ri-search-line"),
    select("ri-checkbox-line", "ri-checkbox-line"),
    select1("ri-checkbox-line", "ri-checkbox-line"),
    setup("ri-settings-line", "ri-settings-line"),
    shouhou("ri-headphone-line", "ri-headphone-line"),
    star("ri-star-line", "ri-star-line"),
    settingprj("ri-settings-line", "ri-settings-line"),
    theme("ri-palette-line", "ri-palette-line"),
    tool("ri-tools-line", "ri-tools-line"),
    unkown("ri-question-line", "ri-question-line"),
    tools("ri-tools-line", "ri-tools-line"),
    values("ri-list-ordered", "ri-list-ordered"),
    ivideo("ri-video-line", "ri-video-line"),
    var("ri-code-line", "ri-code-line"),
    vmirror("ri-arrow-up-down-line", "ri-arrow-up-down-line"),
    shukongjian("ri-stack-line", "ri-stack-line"),
    viewpoint("ri-eye-line", "ri-eye-line"),
    action("ri-play-line", "ri-play-line"),
    x("ri-close-line", "ri-close-line"),
    wbdiconsoftswf("ri-file-pdf-line", "ri-file-pdf-line"),
    action1("ri-play-circle-line", "ri-play-circle-line"),
    addpath("ri-add-box-line", "ri-add-box-line"),
    alignh("ri-align-center", "ri-align-center"),
    alignl("ri-align-left", "ri-align-left"),
    alignc("ri-align-center", "ri-align-center"),
    alignm("ri-align-justify", "ri-align-justify"),
    aligncell("ri-table-line", "ri-table-line"),
    alignt("ri-align-top", "ri-align-top"),
    alignwh("ri-expand-up-down-line", "ri-expand-up-down-line"),
    alingb("ri-align-bottom", "ri-align-bottom"),
    alignw("ri-fullscreen-line", "ri-fullscreen-line"),
    array("ri-list-check", "ri-list-check"),
    app("ri-smartphone-line", "ri-smartphone-line"),
    arrow("ri-arrow-right-line", "ri-arrow-right-line"),
    audio("ri-volume-up-line", "ri-volume-up-line"),
    breakpath("ri-link-unlink", "ri-link-unlink"),
    astext("ri-font-size", "ri-font-size"),
    cancel("ri-close-line", "ri-close-line"),
    saudio("ri-volume-up-line", "ri-volume-up-line"),
    buttonviews("ri-grid-line", "ri-grid-line"),
    button("ri-checkbox-blank-line", "ri-checkbox-blank-line"),
    block("ri-box-2-line", "ri-box-2-line"),
    buttonview("ri-layout-grid-line", "ri-layout-grid-line"),
    checkbox("ri-checkbox-line", "ri-checkbox-line"),
    iconslist("ri-list-check", "ri-list-check"),
    hiddeninput("ri-key-line", "ri-key-line"),
    imagebutton("ri-image-line", "ri-image-line"),
    image("ri-image-line", "ri-image-line"),
    label("ri-font-size", "ri-font-size"),
    layout("ri-grid-line", "ri-grid-line"),
    input("ri-keyboard-line", "ri-keyboard-line"),
    clear("ri-close-circle-line", "ri-close-circle-line"),
    iconclass("ri-code-line", "ri-code-line"),
    click("ri-cursor-line", "ri-cursor-line"),
    list("ri-list-check", "ri-list-check"),
    closepath("ri-close-circle-line", "ri-close-circle-line"),
    clone("ri-file-copy-line", "ri-file-copy-line"),
    menu("ri-menu-line", "ri-menu-line"),
    menubar("ri-more-line", "ri-more-line"),
    nativebutton("ri-checkbox-blank-line", "ri-checkbox-blank-line"),
    codeview("ri-code-line", "ri-code-line"),
    code("ri-code-line", "ri-code-line"),
    numberinput("ri-hashtag", "ri-hashtag"),
    coin("ri-coin-line", "ri-coin-line"),
    com("ri-plug-line", "ri-plug-line"),
    conf("ri-settings-line", "ri-settings-line"),
    conf1("ri-settings-3-line", "ri-settings-3-line"),
    coms("ri-plug-line", "ri-plug-line"),
    console("ri-terminal-line", "ri-terminal-line"),
    config("ri-settings-line", "ri-settings-line"),
    pager("ri-refresh-line", "ri-refresh-line"),
    panel("ri-stack-line", "ri-stack-line"),
    copy("ri-file-copy-line", "ri-file-copy-line"),
    progressbar("ri-task-line", "ri-task-line"),
    richeditor("ri-edit-line", "ri-edit-line"),
    radiobox("ri-checkbox-circle-line", "ri-checkbox-circle-line"),
    slider("ri-slideshow-line", "ri-slideshow-line"),
    password("ri-lock-line", "ri-lock-line"),
    span("ri-font-size", "ri-font-size"),
    stacks("ri-stack-line", "ri-stack-line"),
    css("ri-css3-line", "ri-css3-line"),
    statusbtns("ri-task-line", "ri-task-line"),
    spinner("ri-loader-line", "ri-loader-line"),
    tabs("ri-table-line", "ri-table-line"),
    statusbutton("ri-toggle-line", "ri-toggle-line"),
    textarea("ri-align-left", "ri-align-left"),
    timeinput("ri-time-line", "ri-time-line"),
    toolbar("ri-tools-line", "ri-tools-line"),
    timer("ri-timer-line", "ri-timer-line"),
    treebar("ri-node-tree", "ri-node-tree"),
    treeview("ri-tree-line", "ri-tree-line"),
    url("ri-link", "ri-link"),
    custom("ri-tools-line", "ri-tools-line"),
    com2("ri-plug-line", "ri-plug-line"),
    com3("ri-plug-line", "ri-plug-line"),
    mqtt("ri-base-station-line", "ri-base-station-line"),
    
    // ood 图标升级
    ood("ri-box-2-line", "ri-box-2-line"),
    placeholder("ri-map-pin-line", "ri-map-pin-line"),
    iempty("ri-box-2-line", "ri-box-2-line"),
    loading("ri-loader-line", "ri-loader-line"),
    istar("ri-star-line", "ri-star-line"),
    smill("ri-emotion-line", "ri-emotion-line"),
    trash("ri-delete-bin-line", "ri-delete-bin-line"),
    error("ri-error-warning-line", "ri-error-warning-line"),
    back("ri-arrow-left-line", "ri-arrow-left-line"),
    bold("ri-bold", "ri-bold"),
    bgcolor("ri-paint-fill", "ri-paint-fill"),
    breaklink("ri-link-unlink", "ri-link-unlink"),
    clock("ri-time-line", "ri-time-line"),
    circle("ri-checkbox-blank-circle-line", "ri-checkbox-blank-circle-line"),
    ibigup("ri-arrow-up-line", "ri-arrow-up-line"),
    icode("ri-code-line", "ri-code-line"),
    idialog("ri-window-line", "ri-window-line"),
    bullet("ri-checkbox-blank-circle-line", "ri-checkbox-blank-circle-line"),
    date("ri-calendar-line", "ri-calendar-line"),
    dragadd("ri-add-line", "ri-add-line"),
    dragmove("ri-drag-move-line", "ri-drag-move-line"),
    dragcopy("ri-file-copy-line", "ri-file-copy-line"),
    dropdown("ri-arrow-down-s-line", "ri-arrow-down-s-line"),
    dragstop("ri-stop-line", "ri-stop-line"),
    ifile("ri-file-line", "ri-file-line"),
    expand("ri-arrow-down-s-line", "ri-arrow-down-s-line"),
    fold("ri-arrow-right-s-line", "ri-arrow-right-s-line"),
    filter("ri-filter-line", "ri-filter-line"),
    font("ri-font-size", "ri-font-size"),
    forecolor("ri-palette-line", "ri-palette-line"),
    formatbrush("ri-paint-brush-line", "ri-paint-brush-line"),
    formatclear("ri-eraser-line", "ri-eraser-line"),
    iindent("ri-indent-increase", "ri-indent-increase"),
    ihtml("ri-code-line", "ri-code-line"),
    italic("ri-italic", "ri-italic"),
    link("ri-link", "ri-link"),
    inserthr("ri-subtract-line", "ri-subtract-line"),
    imenu("ri-menu-line", "ri-menu-line"),
    minus("ri-subtract-line", "ri-subtract-line"),
    checked("ri-check-line", "ri-check-line"),
    mobile("ri-smartphone-line", "ri-smartphone-line"),
    mouse("ri-cursor-line", "ri-cursor-line"),
    outdent("ri-indent-decrease", "ri-indent-decrease"),
    picture("ri-image-line", "ri-image-line"),
    print("ri-printer-line", "ri-printer-line"),
    numbers("ri-list-ordered", "ri-list-ordered"),
    right("ri-arrow-right-line", "ri-arrow-right-line"),
    search("ri-search-line", "ri-search-line"),
    question("ri-question-line", "ri-question-line"),
    remove("ri-close-line", "ri-close-line"),
    sort("ri-sort-asc", "ri-sort-asc"),
    ichecked("ri-check-line", "ri-check-line"),
    strikethrough("ri-strikethrough", "ri-strikethrough"),
    sub("ri-subscript", "ri-subscript"),
    iconsuper("ri-superscript", "ri-superscript"),
    transparent("ri-paint-fill", "ri-paint-fill"),
    idown("ri-arrow-down-s-line", "ri-arrow-down-s-line"),
    left("ri-arrow-left-s-line", "ri-arrow-left-s-line"),
    iright("ri-arrow-right-s-line", "ri-arrow-right-s-line"),
    iup("ri-arrow-up-s-line", "ri-arrow-up-s-line"),
    undo("ri-arrow-go-back-line", "ri-arrow-go-back-line"),
    redo("ri-arrow-go-forward-line", "ri-arrow-go-forward-line"),
    upload("ri-upload-line", "ri-upload-line"),
    zoomin("ri-zoom-in-line", "ri-zoom-in-line"),
    zoomout("ri-zoom-out-line", "ri-zoom-out-line"),
    underline("ri-underline", "ri-underline"),
    ierror("ri-error-warning-line", "ri-error-warning-line"),
    refresh("ri-refresh-line", "ri-refresh-line"),
    arrowdrop("ri-arrow-down-s-line", "ri-arrow-down-s-line"),
    check("ri-check-line", "ri-check-line"),
    cichecked("ri-check-line", "ri-check-line"),
    add("ri-add-line", "ri-add-line"),
    iclose("ri-close-line", "ri-close-line"),
    cmdbox("ri-grid-line", "ri-grid-line"),
    cdate("ri-calendar-line", "ri-calendar-line"),
    color("ri-palette-line", "ri-palette-line"),
    cdelete("ri-delete-bin-line", "ri-delete-bin-line"),
    dotted("ri-more-line", "ri-more-line"),
    cdatetime("ri-calendar-event-line", "ri-calendar-event-line"),
    helpinput("ri-question-line", "ri-question-line"),
    getter("ri-list-check", "ri-list-check"),
    cfile("ri-file-line", "ri-file-line"),
    info("ri-information-line", "ri-information-line"),
    land("ri-expand-up-down-line", "ri-expand-up-down-line"),
    max("ri-fullscreen-line", "ri-fullscreen-line"),
    min("ri-fullscreen-exit-line", "ri-fullscreen-exit-line"),
    location("ri-map-pin-line", "ri-map-pin-line"),
    opt("ri-settings-line", "ri-settings-line"),
    pop("ri-external-link-line", "ri-external-link-line"),
    pin("ri-pushpin-line", "ri-pushpin-line"),
    radio("ri-checkbox-circle-line", "ri-checkbox-circle-line"),
    radiochecked("ri-checkbox-circle-line", "ri-checkbox-circle-line"),
    popbox("ri-window-line", "ri-window-line"),
    crefresh("ri-refresh-line", "ri-refresh-line"),
    restore("ri-window-line", "ri-window-line"),
    cremove("ri-close-line", "ri-close-line"),
    time("ri-time-line", "ri-time-line"),
    cselect("ri-checkbox-line", "ri-checkbox-line"),
    csave("ri-save-line", "ri-save-line"),
    toggle("ri-toggle-line", "ri-toggle-line"),
    togglechecked("ri-toggle-fill", "ri-toggle-fill"),
    alingleft("ri-align-left", "ri-align-left"),
    aligncenter("ri-align-center", "ri-align-center"),
    alignjustify("ri-align-justify", "ri-align-justify"),
    alignright("ri-align-right", "ri-align-right"),
    singleleft("ri-arrow-left-s-line", "ri-arrow-left-s-line"),
    singleright("ri-arrow-right-s-line", "ri-arrow-right-s-line"),
    singleup("ri-arrow-up-s-line", "ri-arrow-up-s-line"),
    singledown("ri-arrow-down-s-line", "ri-arrow-down-s-line"),
    smalldown("ri-arrow-down-s-line", "ri-arrow-down-s-line"),
    smallup("ri-arrow-up-s-line", "ri-arrow-up-s-line"),
    arrowleft("ri-arrow-left-line", "ri-arrow-left-line"),
    arrowright("ri-arrow-right-line", "ri-arrow-right-line"),
    carrowtop("ri-arrow-up-line", "ri-arrow-up-line"),
    arrowbottom("ri-arrow-down-line", "ri-arrow-down-line"),
    circleleft("ri-arrow-left-circle-line", "ri-arrow-left-circle-line"),
    circleright("ri-arrow-right-circle-line", "ri-arrow-right-circle-line"),
    circleup("ri-arrow-up-circle-line", "ri-arrow-up-circle-line"),
    circledown("ri-arrow-down-circle-line", "ri-arrow-down-circle-line"),
    doubleleft("ri-arrow-left-double-line", "ri-arrow-left-double-line"),
    doubleright("ri-arrow-right-double-line", "ri-arrow-right-double-line"),
    doubleup("ri-arrow-up-double-line", "ri-arrow-up-double-line"),
    doubledown("ri-arrow-down-double-line", "ri-arrow-down-double-line"),
    first("ri-skip-back-line", "ri-skip-back-line"),
    prev("ri-arrow-left-line", "ri-arrow-left-line"),
    next("ri-arrow-right-line", "ri-arrow-right-line"),
    last("ri-skip-forward-line", "ri-skip-forward-line"),
    number("ri-hashtag", "ri-hashtag"),
    
    // 数字图标
    number0("ri-number-0", "ri-number-0"),
    number1("ri-number-1", "ri-number-1"),
    number2("ri-number-2", "ri-number-2"),
    number3("ri-number-3", "ri-number-3"),
    number4("ri-number-4", "ri-number-4"),
    number5("ri-number-5", "ri-number-5"),
    number6("ri-number-6", "ri-number-6"),
    number7("ri-number-7", "ri-number-7"),
    number8("ri-number-8", "ri-number-8"),
    number9("ri-number-9", "ri-number-9");

    private String type;
    private String name;
    private String value;
    private String imageClass;


    CustomImageType(String imageClass, String value) {
        this.type = name();
        this.name = imageClass;
        this.value = value;
        this.imageClass = imageClass;
    }

    @Override
    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @Override
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    @Override
    public String getImageClass() {
        return imageClass;
    }

    public void setImageClass(String imageClass) {
        this.imageClass = imageClass;
    }
}
