apiVersion: agent.ooder.net/v1
kind: SceneDescription

metadata:
  category: MSG
  name: Message Service
  version: 1.0.0
  author: ooder-team
  createdAt: 1708329600000
  updatedAt: 1708329600000

spec:
  category: MSG
  description: 消息服务场景，提供消息发送、队列管理、订阅发布能力
  homepage: https://gitee.com/ooderCN/scene-engine
  license: Apache-2.0
  
  capabilities:
    - name: message-operations
      description: 消息操作能力
      version: 1.0.0
    - name: queue-operations
      description: 队列操作能力
      version: 1.0.0
    - name: subscription-operations
      description: 订阅操作能力
      version: 1.0.0
      
  protocols:
    - type: amqp
      description: AMQP 协议
    - type: mqtt
      description: MQTT 协议
    - type: http
      description: REST API
      
  dependencies: []
  
  roles:
    - name: admin
      capabilities: ["*"]
      description: 管理员角色
    - name: publisher
      capabilities: ["message-operations:send", "queue-operations:read"]
      description: 发布者角色
    - name: subscriber
      capabilities: ["message-operations:receive", "subscription-operations"]
      description: 订阅者角色
      
  interfaces:
    main:
      type: yaml
      location: embedded
      path: interface.yaml
      
  fallback:
    enabled: true
    implementation: net.ooder.scene.drivers.msg.MsgFallback
    description: 本地内存队列降级实现
    limitations:
      - 消息存储在内存中，重启丢失
      - 不支持持久化
      - 不支持集群
